apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-example-rules
  labels:
    app: prometheus-operator  # important for autoscraping through the operator
    release: promo            # important for autoscraping through the operator
    prometheus: example
    role: alert-rules         # important for autoscraping through the operator
  namespace: monitoring
spec:
  groups:
  - name: ./example.rules
    rules:
    - alert: ExampleAlert
      expr: probe_success{job="blackbox-exporter-service"} == 0
      for: 3m
      annotations:
        message: 'Target instance is down'
      labels:
        severity: critical
